### PR TITLE
feat: enable getPageAsImage to render storage annotations

### PR DESCRIPTION
**Pull request by AlessandroDeNard**
Added AnnotationMode enum to project;
Added AnnotationMode to getPageAsImage for also rendering storage annotations;
Added getPageAsCanvas for better utility.

### CODE REVIEW

**Comment by stephanrauh** [comment]
Awesome! I wasn't aware that's possible. Thanks for sending a pull request!

Is it ready for merging?

One minor remark: You've added question marks without removing the `| undefined` bit. As far as I know, that's redundant, so I'd like to remove the `| undefined` from the type. What's your opinion?

**Comment by stephanrauh** [comment]
I've decided to merge your PR without waiting for your feedback because my next changes modify the service class - and after that, merging might become difficult.

**Comment by AlessandroDeNard** [comment]
I was commiting the `| undefined` fix right away, it seems you don't need it anymore.
Thanks for merging my PR. 
As An FYI: The optional notation `?` and `| undefined` for the majority of use-cases they are redundant, however there are specific cases when `| undefined` need to be added like when checking if the key does exists in an object, like `Object.keys()`, because the optional notation does not set the field to undefined under the hood.
However I don't think that would be the case in the RenderParameters, so there will be no problem.

**Comment by stephanrauh** [comment]
Oops - sorry for causing work I didn't merge because of my impatience...

The `Object.keys()` info is interesting. You never stop learning!

**Pull request merged**
