### PR TITLE
Cache PDF worker

### PR DESCRIPTION
**Pull request by legraina**
Store the worker in PDFViewerApplication. The worker is only reloaded when either the application is re-initialized or the worker source changes.

### CODE REVIEW

**Comment by stephanrauh** [comment]
Merci beaucoup!

**Comment by stephanrauh** [comment]
Your improvement is going to land with version 21.3.0. I'd like to test it more thoroughly, so I haven't published the new version yet, but I've decided to update the showcase. In other words, you can already test your own feature on https://pdfviewer.net/.

Just in case the long list of events confuses you: I've merged your request, but the root source is in the project https://github.com/stephanrauh/pdf.js, so I've copied your changes. Nonetheless, the bottom line is your PR enabled me to bring the new feature almost without thinking and with very little effort. That's just great!

**Comment by stephanrauh** [comment]
Just one question: I'm worried about memory leaks. To be honest, the memory leak is already there, and I'd like to get rid of it. I believe your modification doesn't add a new memory leak. What's your opinion, @legraina?

**Comment by legraina** [comment]
Great. Thanks for the showcase.
I don't think I'm creating new leaks as no new blob/url is created, and the listeners/observers are removed. However, they were not removed on destroy, so I have added that part on my code thanks to your question:
```
  async ngOnDestroy() {
    this.removeCanvasListeners();
    this.stopObservers();
  }
```

**Pull request merged**
