### PR TITLE
add compatibility with angular universal

### PR DESCRIPTION
**Pull request by ebondu**

### CODE REVIEW

**Comment by ebondu** [comment]
Fix https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/213

**Comment by stephanrauh** [comment]
Looks fine by me. I don't understand your changes to `viewer.js` and `viewer-es5.js`. I suppose you didn't really change these files. The changes I'm seeing are my changes. Is that correct? If so, I'd like to merge your PR soon.

Otherwise, I'd have to add your changes to https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/modifyPdfJs/modifyViewer.js first. You know, the base project is Mozilla's pdf.js. I compile it and apply a couple of changes to it. Currently, that's 94 changes, so I wrote a script for that. The script helps me to update when Mozilla releases a new version of pdf.js.

**Comment by leo6104** [comment]
We should not change `viewer.js` and `viewer-es5.js` if it possible. 

I think, we should wrap html in `ngx-extended-pdf-viewer` component file and do not call `doInitPDFViewer()` in ngOnInit in Universal.

```typescript
isBrowser = true;

constructor(
    ...,
    @Inject(PLATFORM_ID) private platformId: string
) {
}

ngOnInit() {
    this.isBrowser = isPlatformBrowser(this.platformId);
    if (this.isBrowser) {
        ... (original implementation)
    }
}
```

```html
<ng-container *ngIf="isBrowser">
   <!-- original html tags -->
</ng-container>
```

With this way, in angular universal, no worker files are loaded, so `viewer.js`/`viewer-es5.js` is not a problem.

**Comment by stephanrauh** [comment]
I've merged your PR and published the version 2.0.0-alpha.12. Please check if everything's OK. Git did weird things during the merge. :)

**Comment by ebondu** [comment]
Hi,
You are right, no need to update pdf / viewer, it was because of my tests.
Your propositions regarding the condition on the init() method should bee relevant, did you tried them ?

**Pull request merged**
