### PR TITLE
Add PdfLoaded and PdfLoadingFailed events

### PR DESCRIPTION
**Pull request by t-mog**
Chain `PDFViewerApplication.open(src, options)` promise to emit events whenever the document loading is completed.
PdfLoaded event contains the number of pages of the document. PdfLoadingFailed event contains the original error from the [viewer.js](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/projects/ngx-extended-pdf-viewer/src/assets/viewer.js#L860).

### CODE REVIEW

**Comment by stephanrauh** [comment]
Your first pull request ever! And as far as I can see, it's a useful one. Congratulations, and thanks a lot!

**Comment by stephanrauh** [comment]
Just one thing: I'd thought that the even `(pagesLoaded)` does the same as your new `(pdfLoaded)` event. Can you tell me the difference?

**Comment by stephanrauh** [comment]
Fun fact: PR #130 is going to be published with version 1.3.0. And I thought publishing bugfix #111 with version 1.1.1 was a funny co-incidence. How often can we repeat this?

**Comment by t-mog** [comment]
Thanks for the quick review of the PR! 

What I found, is that `(pagesLoaded)` is emitted when the document is ready for use and some pages are already rendered, while the `(pdfLoaded)` is emitted earlier, right after the document was fetched. With big documents it makes quite significant difference in time. 

Not exactly sure if there's a difference in pages count value between these two events. I thought that initially it is read from the document properties, and after the document processing it is updated to the actual count (if metadata is corrupted). However, it looks like the `(pagesLoaded)` uses the same property for the number of pages - `pdfDocument.numPages`, that is also returned from the `PDFApplicationViewerApplication.pagesCount` getter ([viewer.js, line 8699](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/77b07ddf16743239de4248e9c089d4835c0661ab/projects/ngx-extended-pdf-viewer/src/assets/viewer.js#L8699)).

**Comment by stephanrauh** [comment]
I guess we should draw a diagram of all these events and document it in https://pdfviewer.net.

**Pull request merged**
