### PR TITLE
Create it.properties

### PR DESCRIPTION
**Pull request by sgabb**
Initial basic aditional translations for italian language

### CODE REVIEW

**Comment by sgabb** [comment]
Checking the it viewer properties [this](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/53a6986efc8c0ca4282fd9efd7a11b41a38de3b7/projects/ngx-extended-pdf-viewer/src/assets/locale/it/viewer.properties#L384) seems the point where english starts to kick back. Where should it be fixed?

**Comment by stephanrauh** [comment]
Wait, what - every text is given both in Italian and English language? You've got a sharp eye!

**Comment by stephanrauh** [comment]
The root cause is probably that the Italian language pack is the only language packs adding a blank before the "=" character. I was lazy, so I've written a very, very simple parser to read the property files, which fails because of the unexpected blank. My best guess is you'll find (or I'm going to find, depending on who's faster) :) the bug in the file `add-additional-translations.js`.

**Comment by sgabb** [comment]
I am not sure I get exactly what is being done in the [add-additional-translations.js](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/addBaseLanguages/add-additional-translations.js), but if it is getting the current file and rewriting it:
`const originalFilename = '../projects/ngx-extended-pdf-viewer/src/' + folder + '/locale/' + lang + '/viewer.properties';`
than could we just clean the it file from [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/assets/locale/it/viewer.properties#L384) ?

**Pull request merged**
